trigger:
  - master

pool:
  vmImage: "windows-latest"

variables:
  solution: "src/*.sln"

steps:
  - task: NuGetToolInstaller@1
    displayName: "Install NuGet"

  - task: NuGetCommand@2
    displayName: "Restore Packages"
    inputs:
      restoreSolution: "$(solution)"

  - task: DotNetCoreCLI@2
    displayName: "Build (Release)"
    inputs:
      command: "build"
      projects: "$(solution)"
      arguments: "--configuration release"

  - task: DotNetCoreCLI@2
    displayName: "Run Tests"
    inputs:
      command: test
      projects: "$(solution)"
