using System;
using System.IO;

namespace AbfSharp.Sections
{
    public class ProtocolSection : Section
    {
        public readonly Int16 nOperationMode;
        public readonly Single fADCSequenceInterval;
        public readonly byte bEnableFileCompression;
        public readonly UInt32 uFileCompressionRatio;
        public readonly Single fSynchTimeUnit;
        public readonly Single fSecondsPerRun;
        public readonly UInt32 lNumSamplesPerEpisode;
        public readonly UInt32 lPreTriggerSamples;
        public readonly UInt32 lEpisodesPerRun;
        public readonly UInt32 lRunsPerTrial;
        public readonly UInt32 lNumberOfTrials;
        public readonly Int16 nAveragingMode;
        public readonly Int16 nUndoRunCount;
        public readonly Int16 nFirstEpisodeInRun;
        public readonly Single fTriggerThreshold;
        public readonly Int16 nTriggerSource;
        public readonly Int16 nTriggerAction;
        public readonly Int16 nTriggerPolarity;
        public readonly Single fScopeOutputInterval;
        public readonly Single fEpisodeStartToStart;
        public readonly Single fRunStartToStart;
        public readonly UInt32 lAverageCount;
        public readonly Single fTrialStartToStart;
        public readonly Int16 nAutoTriggerStrategy;
        public readonly Single fFirstRunDelayS;
        public readonly Int16 nChannelStatsStrategy;
        public readonly UInt32 lSamplesPerTrace;
        public readonly UInt32 lStartDisplayNum;
        public readonly UInt32 lFinishDisplayNum;
        public readonly Int16 nShowPNRawData;
        public readonly Single fStatisticsPeriod;
        public readonly UInt32 lStatisticsMeasurements;
        public readonly Int16 nStatisticsSaveStrategy;
        public readonly Single fADCRange;
        public readonly Single fDACRange;
        public readonly UInt32 lADCResolution;
        public readonly UInt32 lDACResolution;
        public readonly Int16 nExperimentType;
        public readonly Int16 nManualInfoStrategy;
        public readonly Int16 nCommentsEnable;
        public readonly UInt32 lFileCommentIndex;
        public readonly Int16 nAutoAnalyseEnable;
        public readonly Int16 nSignalType;
        public readonly Int16 nDigitalEnable;
        public readonly Int16 nActiveDACChannel;
        public readonly Int16 nDigitalHolding;
        public readonly Int16 nDigitalInterEpisode;
        public readonly Int16 nDigitalDACChannel;
        public readonly Int16 nDigitalTrainActiveLogic;
        public readonly Int16 nStatsEnable;
        public readonly Int16 nStatisticsClearStrategy;
        public readonly Int16 nLevelHysteresis;
        public readonly UInt32 lTimeHysteresis;
        public readonly Int16 nAllowExternalTags;
        public readonly Int16 nAverageAlgorithm;
        public readonly Single fAverageWeighting;
        public readonly Int16 nUndoPromptStrategy;
        public readonly Int16 nTrialTriggerSource;
        public readonly Int16 nStatisticsDisplayStrategy;
        public readonly Int16 nExternalTagType;
        public readonly Int16 nScopeTriggerOut;
        public readonly Int16 nLTPType;
        public readonly Int16 nAlternateDACOutputState;
        public readonly Int16 nAlternateDigitalOutputState;
        public readonly Single fCellID1;
        public readonly Single fCellID2;
        public readonly Single fCellID3;
        public readonly Int16 nDigitizerADCs;
        public readonly Int16 nDigitizerDACs;
        public readonly Int16 nDigitizerTotalDigitalOuts;
        public readonly Int16 nDigitizerSynchDigitalOuts;
        public readonly Int16 nDigitizerType;

        public ProtocolSection(BinaryReader reader) : base(reader, 76)
        {
            reader.BaseStream.Seek(SectionStart, SeekOrigin.Begin);
            nOperationMode = reader.ReadInt16();
            fADCSequenceInterval = reader.ReadSingle();
            bEnableFileCompression = reader.ReadByte();
            reader.ReadBytes(3);
            uFileCompressionRatio = reader.ReadUInt32();
            fSynchTimeUnit = reader.ReadSingle();
            fSecondsPerRun = reader.ReadSingle();
            lNumSamplesPerEpisode = reader.ReadUInt32();
            lPreTriggerSamples = reader.ReadUInt32();
            lEpisodesPerRun = reader.ReadUInt32();
            lRunsPerTrial = reader.ReadUInt32();
            lNumberOfTrials = reader.ReadUInt32();
            nAveragingMode = reader.ReadInt16();
            nUndoRunCount = reader.ReadInt16();
            nFirstEpisodeInRun = reader.ReadInt16();
            fTriggerThreshold = reader.ReadSingle();
            nTriggerSource = reader.ReadInt16();
            nTriggerAction = reader.ReadInt16();
            nTriggerPolarity = reader.ReadInt16();
            fScopeOutputInterval = reader.ReadSingle();
            fEpisodeStartToStart = reader.ReadSingle();
            fRunStartToStart = reader.ReadSingle();
            lAverageCount = reader.ReadUInt32();
            fTrialStartToStart = reader.ReadSingle();
            nAutoTriggerStrategy = reader.ReadInt16();
            fFirstRunDelayS = reader.ReadSingle();
            nChannelStatsStrategy = reader.ReadInt16();
            lSamplesPerTrace = reader.ReadUInt32();
            lStartDisplayNum = reader.ReadUInt32();
            lFinishDisplayNum = reader.ReadUInt32();
            nShowPNRawData = reader.ReadInt16();
            fStatisticsPeriod = reader.ReadSingle();
            lStatisticsMeasurements = reader.ReadUInt32();
            nStatisticsSaveStrategy = reader.ReadInt16();
            fADCRange = reader.ReadSingle();
            fDACRange = reader.ReadSingle();
            lADCResolution = reader.ReadUInt32();
            lDACResolution = reader.ReadUInt32();
            nExperimentType = reader.ReadInt16();
            nManualInfoStrategy = reader.ReadInt16();
            nCommentsEnable = reader.ReadInt16();
            lFileCommentIndex = reader.ReadUInt32();
            nAutoAnalyseEnable = reader.ReadInt16();
            nSignalType = reader.ReadInt16();
            nDigitalEnable = reader.ReadInt16();
            nActiveDACChannel = reader.ReadInt16();
            nDigitalHolding = reader.ReadInt16();
            nDigitalInterEpisode = reader.ReadInt16();
            nDigitalDACChannel = reader.ReadInt16();
            nDigitalTrainActiveLogic = reader.ReadInt16();
            nStatsEnable = reader.ReadInt16();
            nStatisticsClearStrategy = reader.ReadInt16();
            nLevelHysteresis = reader.ReadInt16();
            lTimeHysteresis = reader.ReadUInt32();
            nAllowExternalTags = reader.ReadInt16();
            nAverageAlgorithm = reader.ReadInt16();
            fAverageWeighting = reader.ReadSingle();
            nUndoPromptStrategy = reader.ReadInt16();
            nTrialTriggerSource = reader.ReadInt16();
            nStatisticsDisplayStrategy = reader.ReadInt16();
            nExternalTagType = reader.ReadInt16();
            nScopeTriggerOut = reader.ReadInt16();
            nLTPType = reader.ReadInt16();
            nAlternateDACOutputState = reader.ReadInt16();
            nAlternateDigitalOutputState = reader.ReadInt16();
            fCellID1 = reader.ReadSingle();
            fCellID2 = reader.ReadSingle();
            fCellID3 = reader.ReadSingle();
            nDigitizerADCs = reader.ReadInt16();
            nDigitizerDACs = reader.ReadInt16();
            nDigitizerTotalDigitalOuts = reader.ReadInt16();
            nDigitizerSynchDigitalOuts = reader.ReadInt16();
            nDigitizerType = reader.ReadInt16();
        }
    }
}
