name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Build
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
      - name: ✨ Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: 🚚 Restore
        working-directory: ./src
        run: dotnet restore
      - name: 🔎 Info
        run: dotnet --info
      - name: 🛠️ Build
        working-directory: ./src
        run: dotnet build
      - name: 🧪 Test
        if: false # 32-bit tests don't work on GitHub Actions anymore
        working-directory: ./src
        run: dotnet test --runtime win-x86
